//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace NRDCL.Models
{
    public partial class Deposit
    {
        [Key]
        public string CustomerID { get; set; }
        public decimal LastAmount { get; set; }
        public decimal Balance { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
