//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace NRDCL.Models
{
    public partial class Order
    {
        public int OrderID { get; set; }

        [ForeignKey("Customer")]
        public string CustomerID { get; set; }

        [ForeignKey("Site")]
        public int SiteID { get; set; }

        [ForeignKey("Product")]
        public int ProductID { get; set; }
        public decimal Quantity { get; set; }
        public decimal OrderAmount { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
        public virtual Site Site { get; set; }

    }
}
